apiVersion: v1
kind: Service
metadata:
  name: lost-found-server-service
spec:
  selector:
    app: lost-found-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
